### ISSUE TITLE
Is Path Constructable ?

### ISSUE THREAD

**Issue by nekooei** [SharifAIChallenge/AIC18-Server#11]
سلام
این متن طبق داکیومنت خودتون هست
«طبیعتاً
امکان ساخت برج در مسیر 
جاده
ها وجود ندارد.»
ولی این قطعه کد درست کار میکند و برج روی مسیر ساخته میشود‌
`Point test = world->get_defence_map_paths()[0]->get_road()[0]->get_location();
    std::cout<<world->is_tower_constructible(test.get_x(), test.get_y()) << std::endl;
    world->create_archer_tower(1,test.get_x(), test.get_y());`
البته نمایشگر بازی که کلا روی اعصابه! معلوم نیس محور نمایشگر چجوری هست !

**Comment by sehraramiz** [comment]
ها راس میگه

**Comment by kiarash96** [comment]
<div dir="rtl">سلام. اگه منظورتون از این که این قطعه کد کار می‌کنه اینه که کلاینت‌ها ارور نمی‌دن کلاینت‌ها کلا چک نمی‌کنن دستوری که شما می‌فرستید به سرور valid هست یا نه. دستوری که به سرور می‌فرستید اگه invalid باشه صرفا ایگنور می‌شه.<br/>
اگه منظورتون اینه که واقعا برج ساخته می‌شه توی اون خونه لطفا لاگ یه بازی رو که توش این اتفاق افتاده بفرستید چون من این کد رو اجرا کردم و اتفاق غیر منتظره‌ای نیفتاد</div>

**Comment by kiarash96** [comment]
سلام. مشکلی در کلاینت سی‌پلاس‌پلاس در این رابطه وجود داشت. لطفا اینجا رو مطالعه کنید:
https://github.com/SharifAIChallenge/AIC18-Client-Cpp/issues/15

**Comment by nekooei** [comment]
این مشکل تا ۱۴ ساعت پیش وجود داشت! امیدوارم عدالت را رعایت کنین و تایم سابمیت رو حداقل تا جمعه تمدید کنین!
