### ISSUE TITLE
باگ گردباد برای زره پوش ها

### ISSUE THREAD

**Issue by AM1648** [SharifAIChallenge/AIC18-Server#12]
گردباد برای سرباز های سبک درست عمل میکند اما روی زره پوش تاثیری ندارد (زره پوش ها بعد از گردباد محو نمیشوند)

**Comment by ali-behjati** [comment]
امکانش هست یک لاگ از بازی خود ارسال نمایید؟

**Comment by AM1648** [comment]
[log.txt](https://github.com/SharifAIChallenge/AIC18-Server/files/1747929/log.txt)
دقت کنید که به دلیل یک باگ دیگر در نمایشگر محل گردباد نسبت به محل واقعی به صورت قرینه نشان داده میشود

**Comment by RuhollahSeka** [comment]
توجه کنید که در هر نوبت ابتدا گردبادها رخ می دهند و سپس سربازها حرکت می کنند، به همین دلیل اگر قبل از حرکت در بازه مورد نیاز گردباد نباشند و بعد از حرکت در آن بازه قرار بگیرند، زنده خواهند ماند. این دقیقا اتفاقی است که در نوبت 5م لاگی که فرستادید رخ میدهد
