### ISSUE TITLE
Money Bug

### ISSUE THREAD

**Issue by seriiix** [SharifAIChallenge/AIC18-Server#13]
در صورتی که در ترن ۱ توپ جنگی با لول بیشتر از لول ۱ ساخته بشه سرور اونو میسازه ولی اندازه یک توپ جنگی لول ۱ پول کم میشه از کلاینت.
یعنی من اگه یک دونه لول ۷ بسازم بازم ۲۰۰ تا پول ازم کم میشه
بر روی نمایشگر هم به اشتباه همون ساختمون لول ۱ نشون داده میشه در حالی که رفتار لولی که ساخته شده رو داره
این باگ روی اخرین نسخه کلاینت سی و سرور وجود داره برای سایر حالت ها تست نکردم شاید برای آرچر هم باگ وجود داشته باشه.

**Comment by RuhollahSeka** [comment]
ممنون از گزارشتون، مشکل حل شد
