### ISSUE TITLE
عدم رعایت زمان شلیک

### ISSUE THREAD

**Issue by ImanHosseini** [SharifAIChallenge/AIC18-Server#3]
البته معلوم نیست این مربوط به نمایشگره یا مربوط به سرور ولی
اگر به نمایش بازی در نمایشگر نگاه کنید, انگار برای توپ جنگی 4 واحد زمانی برای دوباره شلیک کردن رعایت نشده

**Comment by Naghipourfar** [comment]
سلام.
مشکلی که مطرح کردین، چک شد و وجود نداشت.
اگر امکانش هست، یکم دقیقتر توضیح بدید. به نظر میاد که کمتر از ۴ واحد زمانی هست یا بیشتر؟

**Comment by ImanHosseini** [comment]
بنظر میاد مثل کماندار ها هست تایمینگش. یعنی زیادی داره شلیک میکنه
