### ISSUE TITLE
Server Error with CPP Client

### ISSUE THREAD

**Issue by VispaarAriana** [SharifAIChallenge/AIC18-Server#5]
This is shown after some turns:

> Info (JsonSocket): Sending message: {"name":"turn","args":[{"myunits":[[1,"l",1,32,{"x":8,"y":8},2,1,32]],"enemyunits":[[2,"l",1,{"x":5,"y":11}]],"mytowers":[[1,"a",2,{"x":0,"y":0}],[3,"a",1,{"x":2,"y":0}],[5,"c",1,{"x":4,"y":0}],[7,"c",1,{"x":6,"y":0}],[9,"a",1,{"x":8,"y":0}],[11,"a",1,{"x":10,"y":0}],[13,"a",1,{"x":12,"y":0}],[15,"c",1,{"x":14,"y":11}],[16,"c",1,{"x":15,"y":0}],[18,"a",1,{"x":17,"y":0}],[20,"c",1,{"x":19,"y":0}]],"enemytowers":[[36,"a",1,{"x":15,"y":0}]],"players":[[50,50,26,2,0],[50,3,0]],"events":{"deadunits":[],"endofpath":[],"destroyedtowers":[],"beans":[],"storms":[]}}]}
> Info (ClientHandler): Message sending failure
> java.net.SocketException: Broken pipe (Write failed)
> 	at java.net.SocketOutputStream.socketWrite0(Native Method)
> 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
> 	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
> 	at network.JsonSocket.send(JsonSocket.java:113)
> 	at server.network.ClientHandler.lambda$getSender$0(ClientHandler.java:138)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 

Also nothing special client-side:

> Turn = 21
> [Info]      Received shutdown message from server
> [Info]      Closing the connection
>

**Comment by Naghipourfar** [comment]
There was a minor issue in the Jar file which is fixed now. Please download the Jar file again.
