### ISSUE TITLE
سوال درباره نحوه اجرای سرور 

### ISSUE THREAD

**Issue by thinkingparticle** [SharifAIChallenge/AIC18-Server#6]
می خوام سرور از یک حالت وسط بازی شروع بشه. مثلا یه حالت خاص وضعیت بازی رو ذخیره کنم و بعد هروقت خواستم سرور رو دوباره به همون حالت ببرم و بازی رو از اون حالت ادامه بدم. چطور میشه این کار رو کرد؟ 
با فایل jar که دادید فکر نکنم بشه.  برای کد جاواش راهنمایی کنید ممنون میشم.

**Comment by Naghipourfar** [comment]
سلام. ویژگی مورد نظر شما در فایل jar و کد سرور پیاده سازی نشده است.
