### ISSUE TITLE
ایا خانه های اطراف برج تبدیل به خانه مسدود میشوند؟

### ISSUE THREAD

**Issue by mrtaalebi** [SharifAIChallenge/AIC18-Server#7]
قرار بر این است که اطراف خانه های ضلعی برج برجی نتوان ساخت
سوال اینست ایا این خانه ها تبدیل به بلاک میشوند یا همچنان به شکل قبل باقی میمانند
ممنون:)

**Comment by RuhollahSeka** [comment]
به شکل قبل باقی می مانند، یعنی اگر برج مذکور خراب شود، می توان در خانه های اطراف برج ساخت
