### ISSUE TITLE
ارور در فایل لاگ

### ISSUE THREAD

**Issue by Kuzey27** [SharifAIChallenge/AIC18-Server#8]
فک کنم وقتی که بازی هزار ترنه میشه یه مشکلی پیش میاد
چون وقتی توی اون دو تا تابع هوش مصنوعی رو خالی می کنم فایل لاگ خراب میشه

این لاگ بازی :
[Game.txt](https://github.com/SharifAIChallenge/AIC18-Server/files/1710075/Game.txt)

اینم اروری که نمایشگر به خاطر لاگ میده :
![image](https://user-images.githubusercontent.com/33800518/36016438-d96ee1ec-0d6a-11e8-9ec5-0702193d9e87.png)

**Comment by Naghipourfar** [comment]
سلام. ممنون از اطلاع رسانی. مشکل حل شد. لطفا دوباره فایل jar را دریافت کنید.
