### ISSUE TITLE
نتیجه اشتباه و عجیب

### ISSUE THREAD

**Issue by sehraramiz** [SharifAIChallenge/AIC18-Server#9]
سلام, وقت بخیر
ما این بازی رو انجام دادیم و مشکلی که داشتیم این بود که بدون اینکه سربازی به آخر مسیر برسه از استحکام تیم کم میشد
لطفا رسیدگی کنین
باتشکر و سپاس فراوان
[Game (copy).txt](https://github.com/SharifAIChallenge/AIC18-Server/files/1718134/Game.copy.txt)

**Comment by ali-behjati** [comment]
It seems this is game viewer bug and we are working to fix it asap. (There is a heavy unit passing a path not shown in UI). Meanwhile, I suggest you to download latest version of the server (since it seems outdated :D)

**Comment by ali-behjati** [comment]
The issue has been resolved and will be released soon.
